### ISSUE TITLE
"Bower Installs" metric won't be supported by Yeoman 1.0

### ISSUE THREAD

**Issue by vitorbal** [yeoman/insight-dashboard#3]
Since Yeoman no longer wraps bower, we won't be able to monitor Bower installs anymore.
It would be awesome if Bower would add support for Yeoman insight. See twitter/bower#260 for the current discussion.
The only reason I'm keeping the graph in at the moment is to showcase how the insight dashboard would work. But we should should remove this metric as soon as we add more metrics

**Comment by sindresorhus** [comment]
Closing as this repo is deprecated.
