### ISSUE TITLE
Line chart

### ISSUE THREAD

**Issue by vitorbal** [yeoman/insight-dashboard#5]
We will need a line chart for many metrics. Nothing fancy, something similar to the one from google analytics would already be awesome: 
![Screen shot 2013-03-16 at 20 29 55](https://f.cloud.github.com/assets/626038/267253/4caf5e4a-8e70-11e2-92d6-2a45b758d554.png)

**Comment by tomlane** [comment]
Plenty of graph libraries out there :+1:

**Comment by vitorbal** [comment]
@tomlane You are right and starting with 629cae50e3e49e36a6a80246caf24fad12c9c601 we'll start using nvd3 instead of plain d3. This should accelerate the process of setting up new directives/charts

**Comment by aboutaaron** [comment]
@vitorbal what's the appeal of nvd3 over plain d3? Just curious as I'd love to start tackling some of these features pretty soon.

**Comment by aboutaaron** [comment]
@vitorbal ahh I guess I could just read the docs. http://nvd3.org/

Neat stuff.

**Comment by sindresorhus** [comment]
Closing as this repo is deprecated.
