### ISSUE TITLE
Filtering by Time

### ISSUE THREAD

**Issue by vitorbal** [yeoman/insight-dashboard#6]
Ideally all our metrics should be filterable by time. It would be awesome if the dashboard would have one main "control" which filters all other metrics by the select time.
The filtering will be done clientside, using [crossfilter](http://square.github.com/crossfilter/).

**Comment by vitorbal** [comment]
I coded up a very crude filtering functionality for the visitors by day metric using xf, but the whole code is in the MainCtrl controller right now. Yuck.
We also need to think how will the code structure would look like. We could register every dataset which needs filtering to a central "manager" (an ng-service?) so when the user chooses a date range, the manager loops through all the datasets and filters them.

**Comment by vitorbal** [comment]
Alright, starting with commit 0fe8ca1 the architecture seems to be shaping up.

Basically every metric (visitors, installs, etc) is encapsulated in a service which is responsible for preparing the data for the charts. It seems a lot of people take this approach of using services to encapsulate these "models" and it does make a lot of sense.

The service should also expose a `filter` method which will get called from our main controller when it handles the filter action coming from the user

**Comment by sindresorhus** [comment]
Closing as this repo is deprecated.
